//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KyushMyush
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сервер.
    /// </summary>
    // *** Start programmer edit section *** (Сервер CustomAttributes)

    // *** End programmer edit section *** (Сервер CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СерверE", new string[] {
            "IP as \'IP\'",
            "Порт as \'Порт\'",
            "Протокол as \'Протокол\'"})]
    [View("СерверL", new string[] {
            "IP as \'IP\'",
            "Порт as \'Порт\'",
            "Протокол as \'Протокол\'"})]
    public class Сервер : ICSSoft.STORMNET.DataObject
    {
        
        private string fIP;
        
        private int fПорт;
        
        private string fПротокол;
        
        // *** Start programmer edit section *** (Сервер CustomMembers)

        // *** End programmer edit section *** (Сервер CustomMembers)

        
        /// <summary>
        /// IP.
        /// </summary>
        // *** Start programmer edit section *** (Сервер.IP CustomAttributes)

        // *** End programmer edit section *** (Сервер.IP CustomAttributes)
        [StrLen(255)]
        public virtual string IP
        {
            get
            {
                // *** Start programmer edit section *** (Сервер.IP Get start)

                // *** End programmer edit section *** (Сервер.IP Get start)
                string result = this.fIP;
                // *** Start programmer edit section *** (Сервер.IP Get end)

                // *** End programmer edit section *** (Сервер.IP Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сервер.IP Set start)

                // *** End programmer edit section *** (Сервер.IP Set start)
                this.fIP = value;
                // *** Start programmer edit section *** (Сервер.IP Set end)

                // *** End programmer edit section *** (Сервер.IP Set end)
            }
        }
        
        /// <summary>
        /// Порт.
        /// </summary>
        // *** Start programmer edit section *** (Сервер.Порт CustomAttributes)

        // *** End programmer edit section *** (Сервер.Порт CustomAttributes)
        public virtual int Порт
        {
            get
            {
                // *** Start programmer edit section *** (Сервер.Порт Get start)

                // *** End programmer edit section *** (Сервер.Порт Get start)
                int result = this.fПорт;
                // *** Start programmer edit section *** (Сервер.Порт Get end)

                // *** End programmer edit section *** (Сервер.Порт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сервер.Порт Set start)

                // *** End programmer edit section *** (Сервер.Порт Set start)
                this.fПорт = value;
                // *** Start programmer edit section *** (Сервер.Порт Set end)

                // *** End programmer edit section *** (Сервер.Порт Set end)
            }
        }
        
        /// <summary>
        /// Протокол.
        /// </summary>
        // *** Start programmer edit section *** (Сервер.Протокол CustomAttributes)

        // *** End programmer edit section *** (Сервер.Протокол CustomAttributes)
        [StrLen(255)]
        public virtual string Протокол
        {
            get
            {
                // *** Start programmer edit section *** (Сервер.Протокол Get start)

                // *** End programmer edit section *** (Сервер.Протокол Get start)
                string result = this.fПротокол;
                // *** Start programmer edit section *** (Сервер.Протокол Get end)

                // *** End programmer edit section *** (Сервер.Протокол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сервер.Протокол Set start)

                // *** End programmer edit section *** (Сервер.Протокол Set start)
                this.fПротокол = value;
                // *** Start programmer edit section *** (Сервер.Протокол Set end)

                // *** End programmer edit section *** (Сервер.Протокол Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СерверE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СерверE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СерверE", typeof(IIS.KyushMyush.Сервер));
                }
            }
            
            /// <summary>
            /// "СерверL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СерверL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СерверL", typeof(IIS.KyushMyush.Сервер));
                }
            }
        }
    }
}
